; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28319.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Josep\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
